apiVersion: v1
kind: Service
metadata:
  name: ingestion-worker
  namespace: mail-ingestion
spec:
  type: ClusterIP
  selector:
    app: ingestion-worker
  ports:
    - name: http
      port: 8081
      targetPort: 8081
